# This file was generated by GoReleaser. DO NOT EDIT.
cask "caxxxd" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0563bdabf115cce1a3ac50a623d9652113430310bc1604c2046ed937283d7bf0"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c73a2a79d64f2c6719cc56cd23db28a12f4e40f680bd6e56690077b60e832aec"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "caxxxd"
  desc "Terminal wrapper around yt-dlp for downloading video, audio, and subtitles"
  homepage "https://github.com/ballisarium/caxxxd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "caxxxd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caxxxd"]
    end
  end

  # No zap stanza required

end
