# This file was generated by GoReleaser. DO NOT EDIT.
cask "caxxxd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "db65ffad6e83533906353b38ff93c2bd1ece7125b2c42c9a09ca07d3dd666413"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b1ee6b562e47a543a6c305596295976deb517f3b11817adb8932e1acb025d98"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "caxxxd"
  desc "Terminal wrapper around yt-dlp for downloading video and audio"
  homepage "https://github.com/ballisarium/caxxxd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "caxxxd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caxxxd"]
    end
  end

  # No zap stanza required

end
