# This file was generated by GoReleaser. DO NOT EDIT.
cask "caxxxd" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "085f64c43a86eb55c934b816eed7112d117a9cc3d5858894804a52edfbf1a166"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffd280ee949917bc53f432ffb7d51f9b00aba9c22f814015f64e628c94be0039"
      url "https://github.com/ballisarium/caxxxd/releases/download/v#{version}/caxxxd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "caxxxd"
  desc "Terminal wrapper around yt-dlp for downloading video, audio, and subtitles"
  homepage "https://github.com/ballisarium/caxxxd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "caxxxd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caxxxd"]
    end
  end

  # No zap stanza required

end
